# Foreword {.unnumbered}

This book is intended for psychologists and social scientists interested in the modeling of psychological processes using the tools of complex systems research.

The book has three primary objectives. The first is to provide a comprehensive overview of complex systems research, with a particular emphasis on its applications in psychology and the social sciences. The second is to provide skills for complex systems research. Lastly, it strives to foster critical thinking regarding the potential applications of complex systems in psychology.

For many decades, scientists have been studying a wide variety of complex systems. Well-known examples include lasers, tornados, chemical oscillations, ant nests and flocks of birds. These scientists have built mathematical and computational models of these complex systems and developed techniques to study them.

The application of these techniques requires a great deal of mathematical and technical knowledge, but also a deep understanding of the nature of the system. You don't just create a mathematical model off the top of your head. In addition, testing such models requires extensive and reliable quantitative data. The application of complex systems theory to the behavioral and social sciences is therefore not straightforward. Theories are often verbal, and quantitative measurement in these sciences is a longstanding issue. While there has been some reasonable progress over the past 150 years, it is fair to say that the behavioral and social sciences are less mature than the "hard" sciences.

Despite these challenges, I think the application of complex systems theory to the behavioral sciences is imperative. Whether we consider humans in isolation, the billions of interacting neurons in the brain, or the social networks in which we find ourselves, complexity is everywhere. Humans, with their complex brains embedded in various hierarchies of social systems, are the ultimate complex systems.

I believe that we can only succeed in exploring this system by understanding its complexity. We need to apply the tools of complexity science to our field of science, which is in desperate need of breakthroughs. After all, the modern world revolves around human beings who, through language and thought, have created an unimaginably complex world. The greatest danger now is man himself, and progress in the field of psychology is necessary and urgent.

This book requires study. New theoretical concepts are illustrated with simulations and examples. Running the simulations, studying the examples, and solving the exercises will contribute to a deeper understanding of the material. I have used the book's content in a master's course for research-minded students in psychology. I expect quite some background in psychology and its research methods.

I assume only pre-university knowledge of mathematics. An important prerequisite is a basic knowledge of the programming languages R or Python. The book uses R for the simulations and exercises, but Python code is provided in the online version of the book. There are many online resources for learning the basics of these languages. In addition to R or Python, we will use NetLogo, but no prior knowledge of NetLogo is expected. NetLogo is a dedicated programming language for the simulation of complex natural and social phenomena. It is freely available for all major computer platforms.

This book has been made available as open access courtesy of Santa Fe Press, a non-profit publisher. Consistent with this approach, I often cite open sources such as Wikipedia rather than proprietary ones. It should be noted that open sources such as Wikipedia have the potential for content changes, although this is unlikely in the contexts I've referenced. I also use only open source software for the examples and exercises.

It is also good to say that this book is more a book for psychologists who have very limited knowledge of complex systems research than the other way around. Experts in complex systems who wonder how it can be applied in psychology may have to wait for another text.

I have written this book based on 35 years of scientific work in collaboration with fantastic colleagues and co-authors of the many papers. I'm part of the ecosystem of the Psychology department, especially the wonderful methods section, of the University of Amsterdam. Also important is the Institute of Advanced Study in Amsterdam, which has complex systems research as a central theme. In recent years I've also been an external faculty member at the renowned Santa Fe Institute in New Mexico. I am indebted to all of them and to many other colleagues around the world. In my citations, I've made an effort to acknowledge the extensive contributions to this vast field. Nevertheless, I recognize that there may be omissions, for which I apologize.

Han van der Maas, Amsterdam 2024
